spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${MARIA_DB_HOST}:${MARIA_DB_PORT}/${MARIA_DB_NAME}
    username: ${MARIA_DB_USERNAME}
    password: ${MARIA_DB_PASSWORD}
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1
    fail-on-missing-locations: true