spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${MARIA_DB_HOST}:${MARIA_DB_PORT}/${MARIA_DB_NAME}
    username: ${MARIA_DB_USERNAME}
    password: ${MARIA_DB_PASSWORD}
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1
    fail-on-missing-locations: true
  cloud:
    aws:
      s3:
        bucket: ${AWS_BUCKET}
      region:
        static: ${AWS_REGION}
      stack:
        auto: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${ADMIN_EMAIL_ADDR}
    password: ${ADMIN_EMAIL_PASSWD} 
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true    
firebase:
    key-path: ${FIREBASE_KEY_PATH}

