spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./data/petid;AUTO_SERVER=true
    username: sa
    password:
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1
    fail-on-missing-locations: true
    locations: classpath:db.migration.h2
  jpa:
    hibernate:
      ddl-auto: none

  cloud:
    aws:
      s3:
        bucket: ${AWS_BUCKET}
      region:
        static: ${AWS_REGION}
      stack:
        auto: false